
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 8000:8000
    depends_on:
      - postgresql

  
  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      depends_on:
        - postgresql

  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgresql
   
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - postgresql

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16