version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    restart: always

  redis:
    image: redis:latest
    container_name: redis_new
    ports:
      - "6379:6379"
    restart: always

  postgresql:
    image: postgres:optimized
    container_name: postgres_new
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgresql
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_new
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    restart: always

volumes:
  postgres_data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16